
on:
  workflow_dispatch:
    inputs:
      name:
        description: your name
        default: Anton
        required: true
        
jobs:
  sayHello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Greeting
      id: greet
      run: echo Hello ${{ github.event.inputs.name }}
