on:
  workflow_dispatch:
    inputs:
      list_of_values:
        description: define a comma-separated list of values
        id: values
        default: 1,2,3

jobs:
  strategy:
    matrix:
      id: [ ${{github.events.input.values}} ]
  
  steps:
    - name: run branches
      with:
        branch_id: ${{ matrix.id }}
      run: echo $branch_id
