on:
  workflow_dispatch:

jobs:
  run_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [ "one", "two", "three" ]
  
    steps:
      - name: run branch ${{ matrix.id }}
        env:
          branch_id: ${{ matrix.id }}
        run: echo This is branch $branch_id
