on:
  workflow_dispatch:
    inputs:
      list_of_values:
        description: define a comma-separated list of values
        id: values
        default: "1,2,3"

jobs:
  run_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [ ${{github.event.inputs.values}} ]
  
    steps:
      - name: run branches
        env:
          branch_id: ${{ matrix.id }}
        run: echo $branch_id
